//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace LastTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Menus = new HashSet<Menu>();
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập tên")]
        public string NameStore { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập địa chỉ")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Nhập 1 đường dẫn file ảnh")]
        public string Avatar { get; set; }
        [Required(ErrorMessage = "Nhập 1 đường dẫn file ảnh")]
        public string Cover { get; set; }
        [Range(1,10,ErrorMessage = "Giới hạn từ 1 đến 10")]
        public Nullable<int> Rep { get; set; }
        [Required]
        public Nullable<double> Latitude { get; set; }
        [Required]
        public Nullable<double> Longtitude { get; set; }
        [Required]
        public string Mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
