//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace LastTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Menus = new HashSet<Menu>();
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Bạn cần phải nhập Tên")]
        public string NameStore { get; set; }
        [Required(ErrorMessage = "Bạn cần phải nhập Địa Chỉ")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Bạn cần phải nhập link file ảnh")]
        public string Avatar { get; set; }
        [Required(ErrorMessage = "Bạn cần phải nhập link file ảnh")]
        public string Cover { get; set; }
        
        public Nullable<int> Rep { get; set; }
         [Required(ErrorMessage = "Bạn cần phải nhập Latitude")]
        public Nullable<double> Latitude { get; set; }
         [Required(ErrorMessage = "Bạn cần phải nhập Longtitude")]
        public Nullable<double> Longtitude { get; set; }
        [StringLength(11,MinimumLength = 10,ErrorMessage = "10 hoặc 11 số")]
        [Required(ErrorMessage = "Bạn cần phải nhập số điện thoại")]
        public string Mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
